language: java
jdk:
- oraclejdk11
services:
- xvfb
script: "mvn cobertura:cobertura"
after_success:
- bash <(curl -s https://codecov.io/bash)
before_script:
- "export DISPLAY=:99.0"
- sleep 3 # give xvfb some time to start
before_install:
- chmod +x mvnw
